version: 2.1

orbs:
   slack: circleci/slack@4.0

# the default pipeline parameters, which will be updated according to the results of the path-filtering orb
parameters:
  run-helloworld:
    type: boolean
    default: false
  run-calculator:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: cimg/node:16.5.0

jobs:
  backend-calculator:
    executor: node
    working_directory: ~/circleci-experiments/calculator
    steps:
      - checkout:
          path: ~/circleci-experiments
      - run:
          name: Clean Install Dependencies
          command: npm i
  backend-helloworld:
    executor: node
    working_directory: ~/circleci-experiments/helloworld
    steps:
      - checkout:
          path: ~/circleci-experiments
      - run:
          name: Clean Install Dependencies
          command: npm i
  backend-calculator-print:
    executor: node
    working_directory: ~/circleci-experiments/calculator
    steps:
      - checkout:
          path: ~/circleci-experiments
      - run:
          name: Executing Calculator app
          command: npm i && npm start
  
workflows:
  calculator:
    when: << pipeline.parameters.run-calculator >>
    jobs:
      - backend-calculator:
          name: calculator install
      - backend-calculator-print:
          name: execute calculator
          requires:
            - calculator install

  
  helloworld:
    when: << pipeline.parameters.run-helloworld >>
    jobs:
      - backend-helloworld:
          name: helloworld install
      - slack/notify:
           event: pass
           template: basic_success_1
           context:
            - circleci-slack
